### ISSUE TITLE
Issue with footer

### ISSUE THREAD

**Issue by ghost** [nileshgulia1/Talks-and-events#3]
When viewed in small size screen, coordinators name(last text line) goes out of the screen.

**Comment by nileshgulia1** [comment]
@tusharc2n  May be I have not made footer responsive you can add respective class to footer .feel free to submit PR

**Comment by rsm23** [comment]
Working on it

**Comment by R0nd** [comment]
The "coordinators" list item lacks spaces, preventing word wrap. I'd PR it, but the list item is absent from the index.js file in your repo.

**Comment by rsm23** [comment]
Please checkout #4

**Comment by nileshgulia1** [comment]
Hello @R0nd.I guess index.js is for React timeline  which I have not applied to the website so that it  could understood by non react users.The timeline is Jquery timeline.

**Comment by nileshgulia1** [comment]
fixed  by #4

**Comment by rsm23** [comment]
Please do not forget to labled the PR bro 👍
